Реализован сервис управления чатами
alenapetraki/chat pull request #2
Opened 2022-04-11 20:55 UTC by alenapetraki

2022-04-12 19:16 UTC, snaffi requested changes

2022-04-12 19:16 UTC, snaffi commented on chats/service/service.go
> +}
Рекомендую возвращать конкретный тип а не интерфейс, потому что метод создает именно инстанс service, а не интерфейс

что будем делать если эта структура реализует несколько интерфейсов? :-) 

Еще типизация может облегчить написание тестов

2022-04-12 19:16 UTC, snaffi commented on chats/service/service.go
> +		return nil, errors.New("type required")
почему при проверке chat мы возвращаем type required ? 

Думаешь есть смысл проверять chat? Это ведь не "пользовательская ошибка", а разработчика, нужно ли защищаться от разработчиков?

2022-04-12 19:16 UTC, snaffi commented on commons/id.go
> +import "github.com/rs/xid"
рекомендую использовать [ulid](https://github.com/oklog/ulid)

он лексикографически сортируемый, это поможет при работе с постгресом сортировать записи по id в порядке добавления

2022-04-12 19:16 UTC, snaffi commented on chats/service/service.go
> +	}
А можем это сделать в транзакции?

2022-04-12 19:16 UTC, snaffi commented on chats/service/service.go
> +	}
рекомендую валидацию вынести в отдельную функцию
будет легче читать код с бизнес логикой и не отвлекаться на валидацию

2022-04-12 19:16 UTC, snaffi commented on chats/service/service.go
> +	// - проверить, что пользователь еще не в чате
проверять не обязательно, можно upsert'ить участников

2022-04-12 19:16 UTC, snaffi commented on chats/storage.go
> +	Close() error
а зачем это?

2022-04-12 19:16 UTC, snaffi commented on chats/storage/postgres/db.go
> +}
по такой логике на каждый storage слой мы будем создавать отдельный пул с базой данных, это плохо потому, что слоев будет много значит будет много пулов следовательно слишком много соединений с бд

по сути в конструктор мы должны передать sql.DB, который шарится между разными storage слоями

2022-04-12 19:16 UTC, snaffi commented on chats/storage/postgres/db.go
> +}
https://github.com/pressly/goose обязательно :-)

2022-04-12 19:16 UTC, snaffi commented on chats/storage/postgres/db.go
> +	deleted bool default false
лучше использовать timestamp 
сможем узнать когда было удаление

2022-04-12 19:16 UTC, snaffi commented on chats/storage/postgres/db.go
> +	}
рекомендую использовать query builder для таких целей

его можно использовать не только для построения динамических запросов, но и для статических

https://github.com/doug-martin/goqu

https://github.com/Masterminds/squirrel

2022-04-12 19:16 UTC, snaffi commented on chats/storage/postgres/db.go
> +	row := s.db.QueryRowContext(ctx, `select role from "member" where chat_id=$1 and user_id=$2`, chatID, userID)
а зачем название таблицы в кавычках?

2022-04-12 19:16 UTC, snaffi commented on chats/storage/postgres/db_test.go
> +		})
это разные тестовые сценарии и надо вынести в отдельные тест функции

текущий подход, плохо масштабируется. Кода будет много, вложенность будет большой. Тяжело будет читать

2022-04-26 18:53 UTC, alenapetraki commented on storage/db.go
> +}
Вообще реализовала, когда делала транзакции. Но по идее это дает возможность использовать любое хранилище - нужно только будет сделать адаптер под интерфейс 
Но аргумент работает для sql-БД, монгу под этот интерфейс уже не подстроишь.
если это плохое решение, как реализовать транзакции?)

2022-04-26 18:53 UTC, alenapetraki commented on storage/migrations/files/20220419230629_initial_schema.sql
> +);
может и не особо нужно, но посмотреть было интересно:)

2022-04-26 18:53 UTC, alenapetraki commented on commons/id.go
> +import "github.com/rs/xid"
заменила

2022-04-26 18:53 UTC, alenapetraki commented on account/service.go
> +}
получается, где реализация хранилища нужно описать еще одну структуру с тэгами
"не очень хорошо" - это общепринятая практика для чистоты кода или есть реальные аргументы против?

2022-04-26 18:53 UTC, alenapetraki commented on account/service.go
> +}
вынесла. не понимаю, что будет еще в `models/`

2022-04-26 18:54 UTC, alenapetraki commented on chats/storage.go
> +	Close() error
ээ. я без понятия

2022-04-26 18:54 UTC, alenapetraki commented on chats/storage/postgres/db.go
> +}
да, верно. не понимаю, почему так сделала)

2022-04-26 18:54 UTC, alenapetraki commented on chats/storage/postgres/db.go
> +}
мне даже в голову не пришло, что инициализация это тоже миграция! 🤦🏻‍♀️ 
добавила

2022-04-26 18:54 UTC, alenapetraki commented on chats/storage/postgres/db.go
> +	row := s.db.QueryRowContext(ctx, `select role from "member" where chat_id=$1 and user_id=$2`, chatID, userID)
у меня были проблемы с работой с таблице с названием `user` , и кажется они решились взятием названия в кавычки. и сделала все по аналогии
пока `user` в этом ПР нет, кавычки убрала. буду разбираться если снова столкнусь

2022-04-26 18:54 UTC, alenapetraki commented on chats/storage/postgres/db_test.go
> +		})
согласна, но пока не успела поправить. написала тесты "на коленке" посмотреть, что вообще что-то работает

2022-05-05 15:23 UTC, snaffi commented on storage/db.go
> +}
транзакция реализуется на уровне хранилища, по сути они будут dummy. В идеале конечно реализовать паттерн unit of work, но он очень сложно и громоздко реализуется в го :-(

2022-05-05 15:23 UTC, snaffi commented on storage/migrations/files/20220419230629_initial_schema.sql
> +);
да штука прикольная, но к сожалению добавлять новые энумы нельзя только через удаление и создание нового энума

это проходит в четыре этапа
1) изменить схему таблиц где используется колонка на тип text
2) удалить энум
3) создать новый энум
4) изменить схему таблиц на использование нового типа

проблема заключается в производительности. Если у тебя в таблице 100500 записией то они все начнут обновляться :-(

2022-05-05 15:23 UTC, snaffi commented on storage/migrations/files/20220419230728_initial_schema.go
> +}
лишняя миграция

2022-05-05 15:23 UTC, snaffi commented on util/id/ulid.go
> +}
я бы не стеснялся создавать источник энтропии каждый раз чтобы не было большого lock contention на единственном мьютексе

2022-05-05 15:23 UTC, snaffi commented on util/id/ulid.go
> +// есть ли разница, работать с ULID или строкой?
по идее нет

2022-05-17 18:31 UTC, alenapetraki commented on storage/migrations/files/20220419230629_initial_schema.sql
> +);
вот это да. опасно
лучше уберу

2022-05-17 18:38 UTC, alenapetraki commented on models/entities/user.go
> +}
не извиняйся!) это я 🤦🏻‍♀️ 

как в итоге ты предлагаешь структура проекта выглядеть?

я вижу так:

|_entities - модели
   |_chat.go 
   |_user.go
|_services - реализации сервисов
   |_chats
      |_service
         |_ ...
      |_interface.go
   |_messages
|_storage
   |_chats
      |_...

2022-05-17 18:47 UTC, alenapetraki commented on storage/db.go
> +}
> транзакция реализуется на уровне хранилища

правильно ли я понимаю, что в нашем конкретно случае если пользователь создает чат, то за установку пользователя участником чата отвечает хранилище?
а это ок с точки зрения логики? хранилище должно быть потупее, нет?

2022-05-17 18:51 UTC, alenapetraki commented on models/entities/chat.go
> +)
сделала

2022-05-17 18:53 UTC, alenapetraki commented on services/chats/interface.go
> +}
я только поняла что ты написал, что транзакция должна быть только на уровне хранилища
если так, то понятно все как сделать, но выше вопрос задала

2022-05-17 19:30 UTC, alenapetraki commented on storage/chats/storage.go
> +		return errors.New("not found")
вынесла обрабатываемые ошибки

2022-05-17 19:34 UTC, alenapetraki commented on storage/db.go
> +}
и что значит dummy?

2022-05-19 16:38 UTC, alenapetraki commented on storage/chats/storage.go
> +}
я согласна, но предлагаю пока забить и идти дальше - ок? мне неохота время на это сейчас тратить 🤔 
в следующем сервисе постараюсь в процессе написания сразу добросовестнее все делать

2022-05-19 16:38 UTC, alenapetraki commented on storage/chats/storage.go
> +}
если не ок, говори!)

2022-05-22 14:18 UTC, snaffi commented on account/service.go
> +}
entitities == models 

выбирай название которое больше нравится

2022-05-22 14:21 UTC, snaffi commented on account/service.go
> +}
структуру рядом с хранилищем надо писать по потребности, например ты используешь ORM или sqlx для автоматического сканирования, то тогда придется создавать структуру так как она начнет содержать функционал относящийся к бд

JSON теги не хорошо оставлять так как можешь случайно sensitive данные наружу вытащить например password (как в твоей структуре). По этому для любых ответов сервера надо создавать свои структуры ну и чтобы точнее контролировать данные которые отдаешь наружу

2022-05-22 14:23 UTC, snaffi commented on storage/db.go
> +}
dummy значит пустышка, например если будешь делать хранилище для кассандры то транзакций настоящих не будет, метод запуска транзакций будет запускаться без какого либо эффекта

> правильно ли я понимаю, что в нашем конкретно случае если пользователь создает чат, то за установку пользователя участником чата отвечает хранилище?

совсем не понял, это к чему?

2022-05-22 14:23 UTC, snaffi commented on models/entities/user.go
> +}
мне по нраву

2022-05-22 14:25 UTC, snaffi commented on services/chats/interface.go
> +}
функция норм, но я обычно имею обертку над sql.DB которая имеет метод RunTx

2022-05-22 14:29 UTC, snaffi commented on commons/postgres/connect.go
> +	}
мне очень нравится этот пакет для валидации данных

https://github.com/go-ozzo/ozzo-validation

2022-05-24 19:05 UTC, alenapetraki commented on services/chats/interface.go
> +}
сделала как обсудили в чате

2022-05-29 19:31 UTC, snaffi approved these changes

2022-05-29 19:31 UTC, snaffi commented on services/chats/service/service.go
>  //}
настоятельно рекомендую оборачивать ошибки. Я использую следующий паттерно

```go
func (s *AwesomeService) DoSomething() error {
    const op = "AwesomeService.DoSomething"
    if err := s.dao.Insert(); err != nil {
        return errors.Wrap(op, err)
    }
}

func (d *DAO) Insert() error {
    const op = "DAO.Insert"

     if err := d.DB.Exec(); err != nil {
          return errors.Wrap(op, err)
     }
}

```

таким образом получатся краивые, читаемые и легко отлаживаемые ошибки `AwesomeService.DoSomething: DAO.Insert: postgresql dial error`

в твоем подходе об ошибках мы увидим в логах сообщения об ошибкам с storage, но не поймем где в service это случилось

2022-05-29 19:31 UTC, snaffi commented on storage/migrations/files/20220419230629_initial_schema.sql
>      name varchar(100),
я за то чтобы на уровне бд не было "бизнес логики"
я считаю, что валидация длины должна происходит в приложении а не в базе

2022-06-03 15:43 UTC, merged